// Generated by Selenium IDE

import org.junit.Assert;
import org.junit.Assert.*;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import service.Setup;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

public class AndersenAuthPostMsgTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = Setup.setUpDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void andersenAuthPostMsg() throws InterruptedException {
        driver.get("https://learn.andersenlab.com/");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.id("username")).click();
        driver.findElement(By.id("username")).sendKeys("spiritusdentatus");
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys("237534096Gaz!~");
        Assert.assertEquals("Ошибка при вводе логина", "spiritusdentatus", driver.findElement(By.name("username")).getAttribute("value"));
        Assert.assertEquals("Ошибка при вводе пароля", "237534096Gaz!~", driver.findElement(By.name("password")).getAttribute("value"));
        driver.findElement(By.cssSelector(".btn-primary")).click();
        driver.findElement(By.cssSelector(".iconsmall")).click();
    }
}
